eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8079

spring:
  application:
    name: zuul

management:
  endpoints:
    web:
      exposure:
        include: '*'

zuul:
  routes:
    user-service:
      path: /user-service/**
